### ISSUE TITLE
Create function (buildopencv.cmake) which download and extract opencv/opencv_contrib sources  

### ISSUE THREAD

**Issue by zerofivefiveseven** [TimPushkin/FeatureDetectAndroid#16]
Actually, exactly the same code is used here twice. You can create a function for this -- something like `function(get_opencv repo)` where `repo` argument will be either `opencv` or `opencv_contrib` (this one argument seems to be enough).

_Originally posted by @TimPushkin in https://github.com/TimPushkin/FeatureDetectAndroid/pull/13#discussion_r928208892_

**Comment by TimPushkin** [comment]
Solved in #13
